### ISSUE TITLE
[Testing] Start making test cases (and travis setup) backend agnostic.

### ISSUE THREAD

**Issue by sven1977** [rlgraph/rlgraph#18] opened 2018-11-29 07:57 UTC
Problem: We currently automatically test mostly the tf-versions of our Components and Agents. PyTorch is not well represented in our test cases, which can lead to uncaught bugs. E.g. our travis testing container is tf-based and does not even have PyTorch installed.

Solution: Start converting all test cases from currently pure tf-based to a more flexible setup, where the same test case can be used on both backends. Note that most tests should already be working under both backends, but this needs to be - yes - tested.

**Comment by michaelschaarschmidt** [comment] 2018-11-29 08:38
The problem is different ways of handling batch ranks e.g. in neural networks. This might however change in PyTorch 1.0. 

One option is to handle shape conversions in the main test class (if it's always the same conversion).

**Comment by michaelschaarschmidt** [comment] 2019-02-22 10:06
Have begun moving torch tests into travis, and pending some special cases can start moving other tests soon.

**Closed by michaelschaarschmidt** 2019-02-22 10:06 UTC
